---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-openldap_symas_installation.yml'
  ansible.builtin.import_playbook: playbook-openldap_symas_installation.yml
